version: '3'

dotenv: ['m3u8.env']

tasks:
  build:
    cmds:
      - env GOOS=linux GOARCH=amd64 go build -o ./build/linux-amd64/m3u8 main.go
      - env GOOS=darwin GOARCH=amd64 go build -o ./build/macos-amd64/m3u8 main.go
    silent: false
  generate:
    cmds:
      - sqlc generate
    silent: false
  migrate:up:
    cmds:
      - echo {{.DB_URI}}
      - migrate -path=migrations -database {{.DB_URI}} up
  migrate:version:
    cmds:
      - echo {{.DB_URI}}
      - migrate -path=migrations -database {{.DB_URI}} version
  migrate:down:
    cmds:
      - echo {{.DB_URI}}
      - migrate -path=migrations -database {{.DB_URI}} down 1
  migrate:new:
    cmds:
      - migrate create -ext sql -dir migrations {{.CLI_ARGS}}
